### ISSUE TITLE
[REFACTOR] Material design

### ISSUE THREAD

**Issue by Norinot** [Norinot/Angular-Akademia-Team-1#12]
## Summary
A company-wide decision was made that all projects should move to Material Design.

The task is to refactor the entire application with Angular Material components.

## Technical details
- create a new branch: week1
- the week1 branch should preserve the pre-refactor state
- Before the refactor, write unit tests for the most important features
- After the reafactor, all unit tests must pass.

**Comment by Norinot** [comment]
completed in the following two commits 5fe7617fa2326be8701b4f03cabace97f05851e3  , e8790e230985e9c0124da802b1e0bacf6dd3256a

**Comment by zsofip** [comment]
tests completed in week-1 commit cdeb695 and main commit 2cc07f2
