### ISSUE TITLE
Stick notes aligning

### ISSUE THREAD

**Issue by zsofip** [Norinot/Angular-Akademia-Team-1#8]

**Comment by zsofip** [comment]
Dependency
This story is dependent on https://github.com/vblaskovics/AngularAkademia2022/issues/8

Summary
As a user I would like to align my stick notes horizontally and vertically.

Details
use icons to set the alignment rules. Example:
image
necessary options:
horizontally:
left
right
center
justify
vertically
top
bottom
center
justify
Technical details
In flex there is no such thing as "justify align" use space-between or space-around instead

Learning materials
[Learn Flexbox in 15 Minutes](https://www.youtube.com/watch?v=fYq5PXgSsbE)
[Flexbox Playground](https://flexbox.tech/)
[Cheatsheet](https://yoksel.github.io/flex-cheatsheet/)

**Comment by Norinot** [comment]
done in  158670f40a842ca07dab8c6704aa1d39ad5a9e49 and 4af6185a5bb07463fbdf2be255cf64a1c8c72b52 commits
